config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :customers
  resources :conversations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :customer

  validates :comment, presence: true, length:{ minimum: 5}
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :lastName, presence: true
  validates :cellPhone, presence: true
  validates :email, presence: true
  validates :state, presence: true, length:{ minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
      @conversations = Conversation.all
    end

    def new
      @conversation = Conversation.new
    end

  def create
      @conversation =  Conversation.new(conversation_params)
      @conversation.user = current_user
      if @conversation.save
        redirect_to conversations_path(@conversation)
      else
        render :new
      end
  end

    private

    def conversation_params
      params.require(:conversation).permit(:comment)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer =  Customer.new(customer_params)
    @customer.user = current_user
    if @customer.save
      redirect_to customers_path(@customer)
    else
      render :new
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :lastName, :cellPhone, :email, :state)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center pt-5">
    <%= link_to 'Agregar Cliente', new_conversation_path, class:"btn btn-primary", style:"width: 200px"%>
  </div>
</div>

app/views/conversations/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-10 offset-lg-1">
      <div class="bg-white rounded p-3 shadow">
        <h1 style="text-align:center;">Comentario</h1>
          <%= simple_form_for [@conversation] do |f| %>
            <%= f.input :comment, prompt: "Comentario", as: :text, class:"", placeholder: "", label: "Comentario"%>
            <%= f.submit class: "btn btn-primary", value:"Subir comentario"%>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<div class="container">
<h1 class="py-5">Prospectos / <%= link_to 'Agregar un nuevo Prospecto', new_customer_path, style:"width: 200px"%></h1>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Apellido</th>
        <th scope="col">Telefono</th>
        <th scope="col">Correo Electronico</th>
        <th scope="col">Estado</th>
        <th scope="col">Conversacion</th>
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <th scope="row"><%= customer.name %></th>
        <td><%= customer.lastName %></td>
        <td><%= customer.cellPhone %></td>
        <td><%= customer.email %></td>
        <td><%= customer.state %></td>
        <td>
          <%= link_to 'Conversacion', new_conversation_path, class:"", style:"width: 200px"%>
        
        </td>
        <td>
          <%= link_to 'Ver', '#', class:"", style:"width: 200px"%>
          <%= link_to 'Editar', '#', class:"", style:"width: 200px"%>
        </td>
      </tr>
      <% end %>
      </tbody>
  </table>
</div>

app/views/customers/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-10 offset-lg-1">
      <div class="bg-white rounded p-3 shadow">
        <h1 style="text-align:center;">Post</h1>
        
          <%= simple_form_for [@customer] do |f| %>
            <%= f.input :name, prompt: "Nombre", class:"", placeholder: "", label: "Nombre"%>
            <%= f.input :lastName, prompt: "Apellido", class:"", placeholder: "", label: "Apellido"%>
            <%= f.input :cellPhone, prompt: "Telefono", class:"", placeholder: "", label: "Telefono"%>
            <%= f.input :email, prompt: "Correo Electronico", class:"", placeholder: "", label: "Correo Electronico"%>
            <%= f.input :state, prompt: "Estado", class:"", placeholder: "", label: "Estado"%>
            <%= f.submit class: "btn btn-primary", value:"Crear Cliente"%>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExequielMunozPortalCrm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container ">
  <div class="">
    <% if user_signed_in? %>
        <h1 class="text-center pt-5">Bienvenido</h1>
        <h2 class="text-center">Para acceder a la lista de cliente presione el boton</h2>
        <div class="d-flex justify-content-center pt-5">
          <%= link_to 'Agregar Cliente', customers_path, class:"btn btn-primary ", style:"width: 200px"%>
        </div>
        
    <% else %>
        <h1>Bienvenido</h1>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "arcane.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to current_user.email, "#", class: "nav-link" %>
          <% else %>
            <%= link_to "Messages", "#", class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "usuario.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>